service: api
runtime: python
env: flex
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT run:app

runtime_config:
  python_version: 3.6

beta_settings:
    cloud_sql_instances: lambda-182214:europe-west1:lambda-master


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1


skip_files:
- venv
- migrations
- tests
- .cache
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
